version: "2.4"

services:
  postgres:
    image: postgres:15
    container_name: cve_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cve_net

  cve-api:
    build: .
    container_name: cve_fastapi
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      NVD_API_KEY: ${NVD_API_KEY}
      NVD_API_BASE: ${NVD_API_BASE}

    networks:
      - cve_net
    restart: unless-stopped

networks:
  cve_net:
    driver: bridge